int x = 5+5;
println("addition: " + x);
int y = 10/5;
println("division: " + y);
x = 12%3;
println("modulo: " + x);
y = 3*5;
println("multiplication: " + y);
x = 5-5;
println("multiplication: " + x);
boolean DAONE = (false||true) && 65>3;
println("OR " + DAONE);
DAONE = !(false)&&(true);
println("AND " + DAONE);
DAONE = (3<6) != (3>6);
println("LESS THAN " + DAONE);
DAONE = false||(3<6);
println("GREATER THAN " + DAONE);
DAONE = (3<=6) && !(6<=3);
println("LESS THAN OR EQUALS " + DAONE);
DAONE = !(3>=6);
println("GREATER THAN OR EQAUL " + DAONE);
